#!/usr/bin/fish


#ez update script

set -g skip_clean

function _update
  set_color brgreen
  echo "Syncing repositories..."
  set_color normal
  paru -Sy
  if not set -q -g dry_run 
  	set_color brgreen
  	echo "Upgrading packages..."
  	set_color normal
  	paru -Su
  end
  if not set -q -g skip_flatpak
  	set_color brgreen 
  	echo "Updating flatpaks..."
  	set_color normal
  	flatpak update
  end
  if not set -q -g skip_rust
  	set_color brgreen 
  	echo "Updating Rust toolchains..."
  	set_color normal
  	rustup update
  end
end

function _clean
  set_color bryellow
  echo "Cleaning unneeded packages..."
  set_color normal
  paru --clean  
end

function _help
	echo "This is the unfinished help section"
end

function _main
	
#check command line args for flags
getopts $argv | while read -l key value
	
	switch $key
		case c
			set -e -g skip_clean
		case clean
			set -e -g skip_clean
		case r
			set -g skip_rust
		case f
			set -g skip_flatpak
		case d 
			set -g dry_run
		case h
			_help
			return
		case help	
			_help
			return
	end

end
_update

if not set -q -g skip_clean
	_clean
end

echo (set_color green)
echo "---------------"
echo "Update Complete"
echo "---------------"
echo (set_color normal)
end
_main $argv
