#!/usr/bin/fish


#ez update script

#gotta get them args
set args (getopt -s sh -l "clean" -o "c" abc: $argv)
set args (fish -c "for el in $args; echo \$el; end")

function update
  set_color brgreen
  echo "Syncing repositories..."
  set_color normal
  paru -Sy
  set_color brgreen
  echo "Upgrading packages..."
  set_color normal
  paru -Su
  set_color brgreen 
  echo "Updating flatpaks..."
  flatpak update
end

function clean
  set_color bryellow
  echo "Cleaning unneeded packages..."
  set_color normal
  paru --clean  
end

update

set i 1
while true
	switch $args[$i]
		case "--clean"
			clean
			
		case "-c"
			clean

		case "abc:"
			break
	end
	set i (math "$i + 1")
end

echo (set_color green)
echo "---------------"
echo "Update Complete"
echo "---------------"
echo (set_color normal)
exit
